#!/usr/bin/env bash
export APP_ENV=developer

function clean_tasker {
    rm -rf ~/.tasker
}

function clean_database {
    rm -rf ~/.tasker/last_migration
    rm -rf ~/.tasker/database.sqlite
}

clean_database
go run main.go --debug $@
